# Reverse dependency check, run before each CRAN submission to catch
# breakage in downstream packages ahead of time (this is how the pmml
# break in the 2.3.0 submission should have been caught before submitting -
# see revdep/problems.md from that run for the exact failure it would have
# flagged).
#
# Requires the revdepcheck package (not on CRAN):
#   pak::pak("r-lib/revdepcheck")
#
# Run from the package root: source("revdep/check.R")
#
# revdep_check() itself overwrites revdep/README.md with a results table each
# run, so don't put anything here you want to keep - this file's comments are
# the place for that.
#
# After it finishes:
#   * revdep/problems.md - reverse dependencies that got *worse* against this
#     version of gbm. This is the one to act on before submitting.
#   * revdep/failures.md - packages that couldn't even be installed/checked.
#   * revdep/cran.md - a ready-to-paste "Reverse dependencies" section for
#     cran-comments.md.
#   * revdep/README.md - regenerated by the tool itself; full summary table.

revdepcheck::revdep_reset()

# CRAN's own incoming checks include packages that merely Suggest gbm (this is
# exactly how the pmml break in the 2.3.0 submission was caught), so check all
# dependency types rather than revdepcheck's Depends/Imports/LinkingTo default.
revdepcheck::revdep_check(
  num_workers = 4,
  dependencies = c("Depends", "Imports", "LinkingTo", "Suggests")
)

# For a quick, targeted check of specific packages instead of the full sweep
# above (e.g. to re-verify just pmml before a submission), revdep_check() has
# no `packages` argument - scope it via revdep_add() instead:
#
#   revdepcheck::revdep_reset()
#   revdepcheck:::db_setup(".")  # revdep_add() needs the schema to already
#                                # exist; revdep_reset() wipes it, and unlike
#                                # revdep_check(), revdep_add() won't recreate
#                                # it itself ("Error: no such table: todo").
#   revdepcheck::revdep_add(packages = "pmml")
#   revdepcheck::revdep_check(num_workers = 2)
