test_that("make_output_nodes works correctly with 1 field", {
  onodes1 <- make_output_nodes(name = list("OutputField"), attributes = list(name = "name3", dataType = "double", optype = "continuous"))
  expect_equal(length(onodes1), 1)
  expect_equal(names(xmlToList(onodes1[[1]]))[1], "name")
  expect_equal(as.character(xmlToList(onodes1[[1]])[1]), "name3")
  expect_equal(names(xmlToList(onodes1[[1]]))[2], "dataType")
  expect_equal(as.character(xmlToList(onodes1[[1]]))[2], "double")
  expect_equal(names(xmlToList(onodes1[[1]]))[3], "optype")
  expect_equal(as.character(xmlToList(onodes1[[1]]))[3], "continuous")
})
